# Generated by Django 5.1 on 2024-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default="No description available", max_length=500),
            preserve_default=False,
        ),
    ]
